---
- name: Create a GCP instance
  hosts: localhost
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
    gcp_project: openenv-l5qgx
    gcp_zone: us-central1-a
  tasks:
    - name: Create a VPC network
      google.cloud.gcp_compute_network:
        name: network-instance
        project: "{{ gcp_project }}"
        auth_kind: serviceaccount
        state: present
      register: network

    - name: Create an IPv4 public IP Address
      google.cloud.gcp_compute_address:
        name: address-instance
        region: us-central1
        project: "{{ gcp_project }}"
        auth_kind: serviceaccount
        state: present
      register: address

    - name: Create the RHEL9 instance
      google.cloud.gcp_compute_instance:
        name: rhel9
        machine_type: n1-standard-1
        disks:
          - auto_delete: 'true'
            boot: 'true'
            initialize_params:
              source_image: projects/rhel-cloud/global/images/rhel-9-v20230131
        network_interfaces:
          - network: "{{ network.selfLink }}"
            access_configs:
              - name: External NAT
                nat_ip: "{{ address.address }}"
                type: ONE_TO_ONE_NAT
        zone: "{{ gcp_zone }}"
        project: "{{ gcp_project }}"
        auth_kind: serviceaccount
        state: present
      register: instance

    - name: Show RHEL9 Instance Details
      debug:
        msg: "The RHEL9 instance is accessible at {{ address.address }}"

