---
- name: Retrieve EC2 Instance Information
  hosts: localhost
  gather_facts: False
  tasks:
    - name: List EC2 Instances
      amazon.aws.ec2_instance_info:
        region: "{{ aws_region }}"
      register: ec2_info

    - name: Display EC2 Information
      debug:
        var: ec2_info.instances
