---
- name: Setup AWS Infrastructure
  hosts: localhost
  gather_facts: False
  collections:
    - amazon.aws

  vars:
    aws_region: us-east-1
    vpc_cidr: "10.0.0.0/16"
    subnet_cidr: "10.0.1.0/24"
    key_name: my-key-pair
    key_file: ~/.ssh/my-key-pair.pem
    security_group_name: my-security-group

  tasks:
    - name: Create VPC
      amazon.aws.ec2_vpc_net:
        name: my_vpc
        cidr_block: "{{ vpc_cidr }}"
        region: "{{ aws_region }}"
        state: present
      register: vpc

    - name: Create Subnet
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        cidr: "{{ subnet_cidr }}"
        az: "{{ aws_region }}a"
        state: present
      register: subnet

    - name: Create Security Group
      amazon.aws.ec2_group:
        name: "{{ security_group_name }}"
        description: "Allow SSH and ICMP"
        vpc_id: "{{ vpc.vpc.id }}"
        region: "{{ aws_region }}"
        rules:
          - proto: tcp
            ports:
              - 22
            cidr_ip: 0.0.0.0/0
          - proto: icmp
            from_port: -1
            to_port: -1
            cidr_ip: 0.0.0.0/0
        state: present
      register: security_group

    - name: Create Key Pair
      amazon.aws.ec2_key:
        name: "{{ key_name }}"
        region: "{{ aws_region }}"
        key_material: "{{ lookup('file', key_file) }}"
        state: present
      register: key_pair

    - name: Output VPC information
      debug:
        msg: 
          - "VPC ID: {{ vpc.vpc.id }}"
          - "VPC CIDR: {{ vpc.vpc.cidr_block }}"

    - name: Output Subnet information
      debug:
        msg: 
          - "Subnet ID: {{ subnet.subnet.id }}"
          - "Subnet CIDR: {{ subnet.subnet.cidr }}"

    - name: Output Security Group information
      debug:
        msg: 
          - "Security Group ID: {{ security_group.group_id }}"
          - "Security Group Name: {{ security_group.group_name }}"

    - name: Output Key Pair information
      debug:
        msg: 
          - "Key Pair Name: {{ key_pair.key.name }}"
          - "Key Pair Fingerprint: {{ key_pair.key.fingerprint }}"

